tasks of 3 & 4 module done
js-tasks-ru/jsbasic-20230302_nicykn pull request #4
Opened 2023-03-30 00:33 UTC by DumblD

2023-03-30 00:34 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-04-03 09:01 UTC, SinimaWath requested changes

2023-04-03 09:01 UTC, SinimaWath commented on 3-module/2-task/index.js
> +    }
filter должен возвращать true/false: `return el <= b && el >= a`

2023-04-03 09:01 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  }, '');
Можно проще переписать:

```
users.filter().map().join('\n')
```

2023-04-03 09:01 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  });
Непонятно зачем тут нужен reduce. Для поиска min/max проще использовать цикл
Примерно так:
```
const minMaxObj = { min: arrNum[0], max: arrNum[0] }
for (let index = 1; index < arrNum.length; index++) {
  if (minMaxObj.min >= current) {
    minMaxObj.min = current;
  }
  
  if (minMaxObj.max <= current) {
      minMaxObj.max = current;

  }
}
```

2023-04-03 16:45 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-04-06 13:10 UTC, SinimaWath requested changes

2023-04-06 13:10 UTC, SinimaWath commented on 5-module/2-task/index.js
> +    }
можно упростить до: `divText.hidden = !divText.hidden`

2023-04-06 13:10 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  function showButton(show, buttonElement) {
Кажется, что функция с названием showButton - должно уметь только показывать кнопку, а у тебя, она еще умеет скрывать. Поэтому не сразу понятно, что функция делает

2023-04-11 20:00 UTC, DumblD commented on 3-module/2-task/index.js
> +    }
Точно, можно же сразу вернуть:
function filterRange(arr, a, b) {
  return arr.filter((el) => {
    return el <= b && el >= a;
  });
}

2023-04-11 20:00 UTC, DumblD commented on 3-module/4-task/index.js
> +  }, '');
Спасибо:
function showSalary(users, age) {
  return users.filter((el) => {
    return el.age <= age;
  })
    .map((el) => {
    return `${el.name}, ${el.balance}`;
  })
    .join('\n');
}

2023-04-11 20:00 UTC, DumblD commented on 3-module/5-task/index.js
> +  });
Да, действительно проще, спасибо
 const minMax = {
    min: arrNum[0],
    max: arrNum[0]
  };
  arrNum.forEach((el) => {
    if (el < minMax.min) {
      minMax.min = el;
    }
    if (el > minMax.max) {
      minMax.max = el;
    }
  });

2023-04-11 20:00 UTC, DumblD commented on 5-module/2-task/index.js
> +    }
Исправил:
toggleTextButton.addEventListener('click', () => {
    divText.hidden = !divText.hidden;
  });

2023-04-11 20:00 UTC, DumblD commented on 5-module/3-task/index.js
> +  function showButton(show, buttonElement) {
Разбил на две функции:

  function showButton(buttonElement) {
    buttonElement.style.display = '';
  }

  function hideButton(buttonElement) {
    buttonElement.style.display = 'none';
  }

2023-04-11 20:06 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-04-13 09:16 UTC, SinimaWath approved these changes

2023-04-13 09:17 UTC, merged